Repository mikke89/RmlUi, pull requests merged in 2021-01, with the labels that each got.

#164 Find element parent by selector
  Include/RmlUi/Core/Element.h
  Source/Core/Element.cpp
Labels: enhancement

#165 Added unsigned int and uint64_t to Variant
  Include/RmlUi/Core/TypeConverter.inl
  Include/RmlUi/Core/Variant.h
  Include/RmlUi/Core/Variant.inl
  Source/Core/Variant.cpp
  Source/Lua/Utilities.cpp
Labels: enhancement

#167 Type name logging on registration failure
  Include/RmlUi/Core/DataTypeRegister.h
  Include/RmlUi/Core/Traits.h
Labels: enhancement

#166 Added support of (smart) pointers as members and added support for "T& getter()" getters
  Include/RmlUi/Core/DataModelHandle.h
  Include/RmlUi/Core/DataTypeRegister.h
  Include/RmlUi/Core/DataVariable.h
  Include/RmlUi/Core/Traits.h
  Source/Core/DataModel.cpp
  Source/Core/DataVariable.cpp
Labels: data binding, enhancement

#171 Fix templates not refreshing their stylesheet
  Source/Core/ElementDocument.cpp
Labels: bug
