Repository mikke89/RmlUi, pull requests merged in 2022-08, with the labels that each got.

#340 Fix Lua object garbage collection bug
  Include/RmlUi/Lua/LuaType.inl
Labels: Lua

#334 Improve .gitignore and LoadDocument and LoadFont documentation
  .gitignore
  Include/RmlUi/Core/Context.h
  Include/RmlUi/Core/Core.h
  Source/Core/Core.cpp
  Source/Core/FontEngineInterface.cpp
Labels: documentation

#350 Fix compilation when return type of `find_first_of` is not `size_t`.
  Source/Core/StyleSheetParser.cpp
Labels: build
