Repository mikke89/RmlUi, pull requests merged in 2023-06, with the labels that each got.

#468 placeholder solution to fix PPI for high-DPI screens: multiplying by dp_ratio
  Include/RmlUi/Core/Unit.h
  Source/Core/ComputeProperty.cpp
  Source/Core/ComputeProperty.h
  Source/Core/Element.cpp
  Source/Core/ElementStyle.cpp
Labels: enhancement

#475 StringUtilities::DecodeRml to use strtoul
  Source/Core/StringUtilities.cpp
Labels: enhancement, build

#478 Lua plugin: Return inserted element from AppendChild and InsertBefore
  Source/Lua/Element.cpp
Labels: Lua
