Repository mikke89/RmlUi, pull requests merged in 2023-07, with the labels that each got.

#484 Allow nested datamodels
  Source/Core/Element.cpp
Labels: data binding

#455 Add support for text-align for text inputs
  Source/Core/Elements/WidgetTextInput.cpp
  Source/Core/Elements/WidgetTextInput.h
  Tests/Data/VisualTests/text_alignment.rml
Labels: enhancement, layout

#491 UnitTests: Fix compilation error on MSVC. Update doctest to v2.4.11.
  Tests/Dependencies/doctest/cmake/common.cmake
  Tests/Dependencies/doctest/cmake/doctest.cmake
  Tests/Dependencies/doctest/cmake/doctestAddTests.cmake
  Tests/Dependencies/doctest/doctest.h
Labels: build

#490 Benchmarks: Fix compile error caused by custom std::string allocator.
  Tests/Source/Benchmarks/BackgroundBorder.cpp
  Tests/Source/Benchmarks/Selectors.cpp
Labels: build
