Repository mikke89/RmlUi, pull requests merged in 2023-11, with the labels that each got.

#533 Include fix at Context.cpp
  Source/Core/Context.cpp
Labels: build

#524 Keyboard / spatial navigation
  Include/RmlUi/Core/Context.h
  Include/RmlUi/Core/Element.h
  Include/RmlUi/Core/ElementDocument.h
  Include/RmlUi/Core/ID.h
  Include/RmlUi/Core/StyleTypes.h
  Samples/assets/invader.rcss
  Samples/basic/demo/data/demo.rml
  Samples/invaders/data/game.rml
  Samples/invaders/data/help.rml
  Samples/invaders/data/high_score.rml
  Samples/invaders/data/options.rml
  Samples/invaders/data/pause.rml
  Samples/invaders/data/start_game.rml
  Samples/invaders/src/ElementGame.cpp
  Samples/invaders/src/EventManager.cpp
  Samples/luainvaders/data/game.rml
  Samples/luainvaders/data/help.rml
  Samples/luainvaders/data/high_score.rml
  Samples/luainvaders/data/main_menu.rml
  Samples/luainvaders/data/options.rml
  Samples/luainvaders/data/pause.rml
  Samples/luainvaders/data/start_game.rml
  Samples/luainvaders/data/window.rml
  Source/Core/Context.cpp
  Source/Core/Element.cpp
  Source/Core/ElementDocument.cpp
  Source/Core/ElementStyle.cpp
  Source/Core/Elements/ElementFormControl.cpp
  Source/Core/Elements/WidgetDropDown.cpp
  Source/Core/Elements/WidgetTextInput.cpp
  Source/Core/Elements/WidgetTextInput.h
  Source/Core/StyleSheetSpecification.cpp
  Tests/Data/VisualTests/navigation_01.rml
  Tests/Data/VisualTests/navigation_02.rml
  Tests/Source/VisualTests/TestNavigator.cpp
  Tests/Source/VisualTests/TestViewer.cpp
  Tests/Source/VisualTests/TestViewer.h
Labels: enhancement

#539 Keep the selection begin index updated
  Source/Core/Elements/WidgetTextInput.cpp
Labels: bug

#543 Implement ability to release arbitrary textures from memory
  Include/RmlUi/Core/Core.h
  Source/Core/Core.cpp
  Source/Core/TextureDatabase.cpp
  Source/Core/TextureDatabase.h
Labels: enhancement

#544 Ignore selection range update when the element is not focused
  Source/Core/Elements/WidgetTextInput.cpp
  Source/Core/Elements/WidgetTextInput.h
Labels: enhancement

#542 Fix the input cursor position for a selection range
  Source/Core/Elements/WidgetTextInput.cpp
Labels: enhancement
