Repository mikke89/RmlUi, pull requests merged in 2024-07, with the labels that each got.

#629 Add Depth Test to GL State Backup - GL3 Renderer
  Backends/RmlUi_Renderer_GL3.cpp
  Backends/RmlUi_Renderer_GL3.h
Labels: backends

#630 Pass the composition to TextInputContext via a parameter
  Backends/RmlUi_Platform_Win32.cpp
  Include/RmlUi/Core/TextInputContext.h
  Source/Core/Elements/WidgetTextInput.cpp
Labels: enhancement

#643 Fix wrong include path in file
  Include/RmlUi/Core/TextInputContext.h
Labels: build
