Repository mikke89/RmlUi, pull requests merged in 2024-10, with the labels that each got.

#683 docs: add BeginFrame and PresentFrame to the example code.
  readme.md
Labels: documentation

#699 Allow custom getter/setter on scoped enum
  Include/RmlUi/Core/DataModelHandle.h
  Tests/Source/UnitTests/DataBinding.cpp
Labels: enhancement, data binding

#684 build: remove OpenGL::GL dependency for GL3 backends
  Backends/CMakeLists.txt
  CMake/DependenciesForBackends.cmake
Labels: build
